# Generated by Django 5.0b1 on 2025-11-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workinghours",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
